### ISSUE TITLE
provide some sort of way to refresh from the repl

### ISSUE THREAD

**Issue by mbriggs** [weavejester/environ#16]
I am sure there is a great reason why this isn't already in the project, but I threw this at the bottom of my user.clj and its quite useful (albeit, a giant hack). 

``` clojure
(ns environ.core)

(defn refresh-env
  []
  (alter-var-root #'env
                  (fn [_]
                    (merge
                     (read-env-file)
                     (read-system-env)
                     (read-system-props)))))
```

I know that wouldnt work in all use-cases, but i think it would be useful as a "dev only" thing a large percentage of the time

**Comment by PetrGlad** [comment]
eviron still reads ".lein-env". Why cannot I do the same and load additional data from my own configuration file (which I currently want :) ?
Maybe dispense with environ.core/env var and make it a function? If anyone cares about efficiency it's possible to defonce resulting value it in user code or use let binding.

**Comment by weavejester** [comment]
Environ isn't a library for reading configuration files; it's a tool for accessing the environment the process has started in. The `.lein-env` file is just a mechanism to allow the environment to be set from Leiningen.

**Comment by PetrGlad** [comment]
Of course it's not for reading files. I am happy to read that file and update System/getProperties in my code. But if I do that it won't affect env value because it is already initialized. If env is a function then I can construct and update it's resulting value however I need. 
Having env value defonced forces me to gather additional external configs elsewhere what kind of defeats the purpose of unifying them with this library.

**Comment by mbriggs** [comment]
The purpose of the lib is to handle environment configuration which may be set at several levels. After this PR i realized what i really wanted was `(merge env (read-str (slurp "./config.clj")))`, which isnt what environ is trying to tackle.

**Comment by weavejester** [comment]
> Having env value defonced forces me to gather additional external configs elsewhere what kind of defeats the purpose of unifying them with this library.

That's not the purpose of this library. This library is designed to provide access to the process environment, it's not a library for reading configuration.

The `.lein-env` file is just an implementation detail that may disappear in future, if a better solution for getting information from active project map presents itself.

**Comment by Quezion** [comment]
Bumping into this a decade later from a different ecosystem --

I'm writing a Babashka based application. Environ still works quite well there. However... Babashka tasks start your app within the same native process as the task runner. This means your env variables are already defined by the time you can run any build-code.

I wanted to use a `dev.env` file for dev presets & consume it via running task `bb dev`

Running `(System/setProperty "foo" "bar")` is supported in Babashka but you can't make environ refresh. So I ended up parsing my `dev.env` file directly, setting properties, & using this hacky snippet to reparse Environ's "env"
```clj
(alter-var-root (var environ.core/env)
                (constantly (environ.core/read-env)))
```

For a cleaner implementation, I could've wrapped Environ's API into my own app's namespace. Though I'm not _supposed_ to use any of the convenient functions in `environ.core` like `sanitize-key`, `sanitize-val`, and `read-env-file`. So I'd need to reimplement those.

----

I'm a longtime fan of this library. I'm happy that I can still use it in the Babashka ecosystem. I understand the author's position stated in this thread; that this library isn't for configuration.

However, there's a school of thought (12 factor app) where you treat your environment as your entire configuration. This simplifies a lot of problems and creates strong symmetry between dev & prod runtimes.

I'd love to consume _only_ Environ in these scenarios instead of having my app read a configuration file & wrap environ at runtime. This means your build process needs to fully read & setup the $ENV from your configuration file. This was easy to do in the old world when using Makefiles + Bash to wrap Clojure invocations but harder in a Babashka build system since it's a shared process with the app runtime.
