### ISSUE TITLE
Use vector as environment variable

### ISSUE THREAD

**Issue by ILoveHubGit** [weavejester/environ#75]
I don't know if I'm using this library correct. But every environment variable from my profiles.clj file gets converted to a string. However I would like to be able to use a vector with some sets in it as an enironment variable. 
Something like
{:env {:my-var [{:key1 "val1" key2 val2} {:key1 "val3" key2 val4}]}}
Within my clojure code I would like to be able to use the [...] part as defined above. Number of sets within the vector might be different based on the deployment of the application.
However, this is read in as a string "[{:key1 \"val1\" :key2 val2} {:key1 \"val3\" :key2 val4}]"

Is there a way to keep this as the defined vector with sets withtout the need to parse this in my application?

**Comment by weavejester** [comment]
No, because environment variables and system properties are stored as strings. The project file can contain data structures, but Environ has to cater for the lowest common denominator. It's best to consider the `:env` key in the project file as just a way of setting environment variables during development.

Environ is purely a library for accessing the environment. It's not a library for parsing configuration.

**Comment by ILoveHubGit** [comment]
Thanks for the clear answer.
I solved my problem by using (read-string (environ.core/env :my-env-variable))
